### ISSUE TITLE
Not working in IE ?

### ISSUE THREAD

**Issue by datepickerUser** [ZPavel/datepicker#2]
Hi-I am using this as a standalone-so i copied the css and js into my html page....when i click on the input field the calendar pops up in chrome and edge but in IE11 it does nothing

**Comment by ZPavel** [comment]
hi man, i wil try to find IE11 somewhere (fully using mac/ubuntu). Until that you can still provide me you error (F12 button to open Developer tools) please.

**Comment by datepickerUser** [comment]
Hi- i did f12 and nothing showing - in edge and chrome the field becomes read-only and the calendar pops up - in IE11 the text box does not become read only and  we can enter text..it appears to be ignoring the addEventlistener

**Comment by ZPavel** [comment]
ok it should work on normal IE11 : https://caniuse.com/#search=addEventListener
why are you using edge? According to statistics, only 2% of people use it on the internet.

**Comment by datepickerUser** [comment]
Ya man you are right but unfortunately we have ie11  ..and our it guys are not interested in allowing any other browser..must be the 2% ha ha

**Comment by datepickerUser** [comment]
Hi. I see u have not made any changes ..it still does not work on ie11.  Any chance u will check and fix  thanks for your help

**Comment by ZPavel** [comment]
can you please tell me if it works on ie11 now with a new fix?

**Comment by datepickerUser** [comment]
it works perfectly on ie11 now....thanks a lot for your help
